name: Build and Upload to Artifactory

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      
      - name: Create ZIP package
        run: |
          mkdir -p package
          cp -r TestAutomation package/
          cd package
          zip -r java-build.zip .      
      

      - name: Upload ZIP to Artifactory
        env:
          ARTIFACTORY_URL: https://trialcyua3p.jfrog.io/artifactory
          REPO: Customizations
          TARGET_NAME: java-build.zip
        run: |
          curl --fail --location --show-error --verbose \
            -H "Authorization: Bearer ${{ secrets.ARTIFACTORY_ACCESS_TOKEN }}" \
            -T "package/java-build.zip" \
            "${ARTIFACTORY_URL}/${REPO}/${TARGET_NAME}"

